[package]
name = "cryoglyph"
description = "Fast, simple 2D text rendering for wgpu. A fork of glyphon for iced."
version = "0.1.0"
edition = "2024"
authors = ["Héctor Ramón Jiménez <hector@hecrj.dev>"]
repository = "https://github.com/iced-rs/cryoglyph"
license = "MIT OR Apache-2.0 OR Zlib"

[dependencies]
wgpu = { version = "=30.0.1", default-features = false, features = ["wgsl"] }
etagere = "0.3.0"
cosmic-text = { git = "https://github.com/hecrj/cosmic-text.git", rev = "6e10ac2ce889f48c9eeb1f19c1340a37d6afae31" }
lru = { version = "0.18.4", default-features = false }
rustc-hash = "2.1.3"
